import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from '@/components/Navbar/Header'
const poppins = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Code Sage | All Problems',
    description: 'Generated by create next app',
}

export default function ProblemsLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Header />
                {children}</body>
        </html>
    )
}
